name: libwebp
description: "A Dart wrapper for libwebp"
version: 0.0.1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  ffi: ^2.1.2
  logging: ^1.2.0
  meta: ^1.11.0

dev_dependencies:
  all_lint_rules_community: ^0.0.40
  ffigen: ^11.0.0
  test: ^1.24.9

libwebp:
  version: 1.3.2
