name: libwebp_platform_ffi_darwin
description: "A new Flutter FFI plugin project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.7.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  objective_c: ^7.0.0
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ^18.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
